# Makefile -- build curriculum chapter PDFs via md2pdf.sh
#
# Every chapter is built with --toc (table of contents). Only chapters that
# embed mermaid diagrams are also built with --mermaid; currently that is just
# week1/chapter1.md.
#
#   make                      build every canonical chapter
#                               (--toc; +--mermaid for chapters that use it)
#   make ch<N>                build a single chapter by number, e.g. make ch7
#   make ch1                  mermaid chapter (week1/chapter1.md)
#   make book                -> full book.pdf of all 30 chapters + the Appendix
#                               (master TOC, title page; APPENDIX=0 to omit)
#   make book-local           -> book-local.pdf, two-level TOC: chapter-only
#                                master "Contents" + a compact per-chapter "Contents"
#   make clean                remove generated chapter *.pdf under curriculum/week*/
#   make lint                 shellcheck md2pdf.sh
#
# The file sets are overridable, e.g.:
#   make CHAPTERS="curriculum/week3/chapter18.md curriculum/week3/chapter19.md"
#   make MERMAID_CHAPTERS="curriculum/week1/chapter1.md curriculum/week3/chapter19.md"

CURRICULUM  ?= curriculum
MD2PDF       := bash $(CURDIR)/md2pdf.sh

# Canonical numbered chapters only -- skips day*.md notes and *_vN drafts.
CHAPTERS ?= $(shell ls $(CURRICULUM)/week*/chapter[0-9]*.md 2>/dev/null | grep -vE '(_v[0-9]+)\.')

# Chapters that render mermaid diagrams -> add --mermaid.
MERMAID_CHAPTERS      ?= $(CURRICULUM)/week1/chapter1.md

# Makefile is not shell; shellcheck misparses the ifeq block below. The real
# lint target only checks md2pdf.sh (see `make lint`).
# shellcheck disable=SC1073,SC1065,SC1064,SC1072
ifeq ($(strip $(T)),)
.DEFAULT_GOAL := all      # bare `make` builds everything
else
.DEFAULT_GOAL := one      # `make T=...` builds that single chapter
endif

## help: show the available targets and how to use them
help:
	@echo "AI Systems Engineering Bootcamp -- make targets"
	@echo
	@echo "  make / all          Build every canonical chapter PDF (--toc; +--mermaid where used)."
	@echo "  make ch<N>          Build one chapter by number, e.g. make ch7."
	@echo "  make one T=<path>   Build one chapter by path, e.g. make one T=week1/chapter1.md."
	@echo "  make book          Assemble the full book -> book.pdf (master TOC, title page)"
	@echo "                     + Appendix (supplemental_docs as Appendix A/B/C)."
	@echo "  make book-local    Assemble the book with a two-level TOC -> book-local.pdf."
	@echo "  make gen-ch        Regenerate the ch<N> target block (after add/remove a chapter),"
	@echo "                     then commit the Makefile."
	@echo "  make lint          shellcheck md2pdf.sh."
	@echo "  make clean         Remove generated chapter *.pdf under curriculum/week*/."
	@echo
	@echo "Per-chapter shorthands ch1..ch30 also exist (build one chapter each)."
	@echo "Overridable variables: CHAPTERS, MERMAID_CHAPTERS, TITLE, AUTHOR, INTRO=0 (omit the Introduction),"
	@echo "                     APPENDIX=0 (omit the Appendix)."
# Build a list of .md files. Each gets --toc, plus --mermaid when its basename
# is listed in MERMAID_CHAPTERS (by basename). md2pdf.sh resolves paths relative to its CWD,
# so we cd into each chapter's directory and pass the basename. A single broken
# chapter is reported but does not abort the rest of the run.
# Usage: $(call RUN,md-list)
define RUN
	@__fail=0; __total=0; \
	for m in $(1); do \
		__f=$$(basename "$$m"); __d=$$(dirname "$$m"); __total=$$((__total + 1)); \
		if printf '%s\n' "$(MERMAID_CHAPTERS)" | while read -r p; do basename "$$p"; done | grep -qxF "$$__f"; then __mf="--mermaid"; else __mf=""; fi; \
		printf 'BUILD %-40s [--toc%s]\n' "$$__f" "$$__mf"; \
		if ! ( cd "$$__d" && $(MD2PDF) --toc $$__mf "$$__f" ); then echo "    !! failed: $$__f" >&2; __fail=$$((__fail + 1)); fi; \
	done; \
	__ok=$$((__total - __fail)); \
	echo "----- built $$__ok/$$__total, $$__fail failed -----"; \
	[ $$__fail -eq 0 ]
endef

## build every canonical chapter
all:
	$(call RUN,$(CHAPTERS))

## build one chapter with auto-detected flags: make ch<N>  |  make one T=week1/chapter1.md
one:
	@if [ -z "$(T)" ]; then echo "usage: make one T=week1/chapter1.md" >&2; exit 1; fi
	$(call RUN,$(T))

## Per-chapter shorthands: make ch<N>  (e.g. make ch7) -- flags auto-detected.
## The ch<N> target list below is generated by tools/regen-ch-targets.py.
### PER-CHAPTER TARGETS (generated by tools/regen-ch-targets.py -- do not edit by hand) ###
## Regenerate this block with: make gen-ch   (after adding/removing a chapter).
.PHONY: all one lint clean book book-local gen-ch help ch1 ch2 ch3 ch4 ch5 ch6 ch7 ch8 ch9 ch10 ch11 ch12 ch13 ch14 ch15 ch16 ch17 ch18 ch19 ch20 ch21 ch22 ch23 ch24 ch25 ch26 ch27 ch28 ch29 ch30

ch1:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter1.md

ch2:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter2.md

ch3:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter3.md

ch4:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter4.md

ch5:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter5.md

ch6:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter6.md

ch7:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter7.md

ch8:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter8.md

ch9:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter9.md

ch10:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter10.md

ch11:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter11.md

ch12:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter12.md

ch13:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter13.md

ch14:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter14.md

ch15:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter15.md

ch16:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter16.md

ch17:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter17.md

ch18:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter18.md

ch19:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter19.md

ch20:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter20.md

ch21:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter21.md

ch22:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter22.md

ch23:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter23.md

ch24:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter24.md

ch25:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter25.md

ch26:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter26.md

ch27:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter27.md

ch28:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter28.md

ch29:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter29.md

ch30:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter30.md

### END PER-CHAPTER TARGETS ###
## Regenerate the per-chapter ch<N> target list from the current chapter files.
## Run: make gen-ch    (refreshes the block, then commit the Makefile.)
gen-ch:
	python3 tools/regen-ch-targets.py

## shellcheck the converter
lint:
	shellcheck md2pdf.sh

## Build the full book: the Introduction front matter + all 30 chapters in one
## PDF (master TOC, title page, book document class, mermaid in ch1), followed
## by the Appendix -- the three supplemental_docs chapters, numbered
## Appendix A/B/C (a raw \appendix marker is injected before the first one).
## Output:
## book.pdf at repo root.  INTRO=0 omits the Introduction; APPENDIX=0 omits
## the Appendix.
##   make book                 -> book.pdf
##   make book TITLE="..." AUTHOR="..."
##   INTRO=0 make book                -> book.pdf without the Introduction
##   APPENDIX=0 make book             -> book.pdf without the Appendix
book:
	bash tools/build-book.sh

## Build the full book with a TWO-LEVEL table of contents instead of the single
## deep master TOC: a short front-matter "Contents" listing only the chapters
## (--toc-depth=1), plus a compact per-chapter "Contents" box printed at the top
## of each chapter that lists that chapter's own ## sections / ### subsections.
## Includes the Introduction as front matter (but not its own local "Contents"
## page) and the Appendix (supplemental_docs as Appendix A/B/C, each with its
## own local "Contents" page).  Output: book-local.pdf at repo root.  This
## replaces the ~30-page master TOC.  INTRO=0 omits the Introduction;
## APPENDIX=0 omits the Appendix.
##   make book-local                   -> book-local.pdf
##   make book-local TITLE="..." AUTHOR="..."
##   INTRO=0 make book-local          -> without the Introduction
##   APPENDIX=0 make book-local       -> without the Appendix
book-local:
	bash tools/build-book-localtoc.sh

## remove generated chapter PDFs
clean:
	@rm -f $(CURRICULUM)/week*/chapter[0-9]*.pdf
