# Makefile -- build curriculum chapter PDFs via md2pdf.sh
#
# Every chapter is built with --toc (table of contents). Only chapters that
# embed mermaid diagrams are also built with --mermaid; currently that is just
# week1/chapter1.md.
#
#   make                      build every canonical chapter
#                               (--toc; +--mermaid for chapters that use it)
#   make ch<N>                build a single chapter by number, e.g. make ch7
#   make ch1                  mermaid chapter (week1/chapter1.md)
#   make clean                remove generated chapter *.pdf under curriculum/week*/
#   make lint                 shellcheck md2pdf.sh
#
# The file sets are overridable, e.g.:
#   make CHAPTERS="curriculum/week3/chapter18.md curriculum/week3/chapter19.md"
#   make MERMAID_CHAPTERS="curriculum/week1/chapter1.md curriculum/week3/chapter19.md"

CURRICULUM  ?= curriculum
MD2PDF       := bash $(CURDIR)/md2pdf.sh

# Canonical numbered chapters only -- skips day*.md notes and *_vN drafts.
CHAPTERS ?= $(shell ls $(CURRICULUM)/week*/chapter[0-9]*.md 2>/dev/null | grep -vE '(_v[0-9]+)\.')

# Chapters that render mermaid diagrams -> add --mermaid.
MERMAID_CHAPTERS      ?= $(CURRICULUM)/week1/chapter1.md

ifeq ($(strip $(T)),)
.DEFAULT_GOAL := all      # bare `make` builds everything
else
.DEFAULT_GOAL := one      # `make T=...` builds that single chapter
endif

# Build a list of .md files. Each gets --toc, plus --mermaid when its basename
# is listed in MERMAID_CHAPTERS (by basename). md2pdf.sh resolves paths relative to its CWD,
# so we cd into each chapter's directory and pass the basename. A single broken
# chapter is reported but does not abort the rest of the run.
# Usage: $(call RUN,md-list)
define RUN
	@__fail=0; __total=0; \
	for m in $(1); do \
		__f=$$(basename "$$m"); __d=$$(dirname "$$m"); __total=$$((__total + 1)); \
		if printf '%s\n' "$(MERMAID_CHAPTERS)" | while read -r p; do basename "$$p"; done | grep -qxF "$$__f"; then __mf="--mermaid"; else __mf=""; fi; \
		printf 'BUILD %-40s [--toc%s]\n' "$$__f" "$$__mf"; \
		if ! ( cd "$$__d" && $(MD2PDF) --toc $$__mf "$$__f" ); then echo "    !! failed: $$__f" >&2; __fail=$$((__fail + 1)); fi; \
	done; \
	__ok=$$((__total - __fail)); \
	echo "----- built $$__ok/$$__total, $$__fail failed -----"; \
	[ $$__fail -eq 0 ]
endef

## build every canonical chapter
all:
	$(call RUN,$(CHAPTERS))

## build one chapter with auto-detected flags: make ch<N>  |  make one T=week1/chapter1.md
one:
	@if [ -z "$(T)" ]; then echo "usage: make one T=week1/chapter1.md" >&2; exit 1; fi
	$(call RUN,$(T))

## Per-chapter shorthands: make ch<N>  (e.g. make ch7) -- flags auto-detected.
## The ch<N> target list below is generated by tools/regen-ch-targets.py.
### PER-CHAPTER TARGETS (generated by tools/regen-ch-targets.py -- do not edit by hand) ###
## Regenerate this block with: make gen-ch   (after adding/removing a chapter).
.PHONY: all one lint clean gen-ch ch1 ch2 ch3 ch4 ch5 ch6 ch7 ch8 ch9 ch10 ch11 ch12 ch13 ch14 ch15 ch16 ch17 ch18 ch19 ch20 ch21 ch22 ch23 ch24 ch25 ch26 ch27 ch28 ch29 ch30

ch1:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter1.md

ch2:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter2.md

ch3:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter3.md

ch4:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter4.md

ch5:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter5.md

ch6:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter6.md

ch7:
	@$(MAKE) --no-print-directory one T=curriculum/week1/chapter7.md

ch8:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter8.md

ch9:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter9.md

ch10:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter10.md

ch11:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter11.md

ch12:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter12.md

ch13:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter13.md

ch14:
	@$(MAKE) --no-print-directory one T=curriculum/week2/chapter14.md

ch15:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter15.md

ch16:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter16.md

ch17:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter17.md

ch18:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter18.md

ch19:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter19.md

ch20:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter20.md

ch21:
	@$(MAKE) --no-print-directory one T=curriculum/week3/chapter21.md

ch22:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter22.md

ch23:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter23.md

ch24:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter24.md

ch25:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter25.md

ch26:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter26.md

ch27:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter27.md

ch28:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter28.md

ch29:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter29.md

ch30:
	@$(MAKE) --no-print-directory one T=curriculum/week4/chapter30.md

### END PER-CHAPTER TARGETS ###
## Regenerate the per-chapter ch<N> target list from the current chapter files.
## Run: make gen-ch    (refreshes the block, then commit the Makefile.)
gen-ch:
	python3 tools/regen-ch-targets.py

## shellcheck the converter
lint:
	shellcheck md2pdf.sh

## remove generated chapter PDFs
clean:
	@rm -f $(CURRICULUM)/week*/chapter[0-9]*.pdf
