#!/usr/bin/env python3
"""Regenerate the per-chapter `ch<N>` target block in the repo-root Makefile.

The ch<N> targets are a static list -- this Makefile targets GNU Make 3.81, whose
$(eval)/$(call) cannot emit multi-line recipes -- so re-run this (or `make gen-ch`)
after adding or removing a chapter, then commit the updated Makefile.
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAKEFILE = os.path.join(ROOT, "Makefile")
BEGIN = "### PER-CHAPTER TARGETS (generated by tools/regen-ch-targets.py -- do not edit by hand) ###"
END   = "### END PER-CHAPTER TARGETS ###"

# Canonical chapter .md files: chapterN.md only, skipping day*.md and *_vN drafts.
files = []
for week in sorted(os.listdir(os.path.join(ROOT, "curriculum"))):
    wd = os.path.join(ROOT, "curriculum", week)
    if not os.path.isdir(wd):
        continue
    for name in sorted(os.listdir(wd)):
        m = re.fullmatch(r"chapter(\d+)\.md", name)   # exact name -> skips *_vN and day*
        if m:
            files.append((int(m.group(1)), f"curriculum/{week}/{name}"))

files = sorted(set(files), key=lambda r: r[0])
names = [f"ch{num}" for num, _ in files]

out = [
    BEGIN,
    "## Regenerate this block with: make gen-ch   (after adding/removing a chapter).",
    ".PHONY: all one lint clean book book-local gen-ch " + " ".join(names),
    "",
]
for num, rel in files:
    out += [f"ch{num}:", "\t@$(MAKE) --no-print-directory one T=" + rel, ""]
out.append(END)
block = "\n".join(out) + "\n"

s = open(MAKEFILE).read()
try:
    i, j = s.index(BEGIN), s.index(END) + len(END) + 1
    s = s[:i] + block + s[j:]
except ValueError:
    s = s.rstrip() + "\n\n" + block
open(MAKEFILE, "w").write(s)
print(f"Updated {MAKEFILE}: {len(names)} ch<N> targets (" + ", ".join(names) + ").")
